### ISSUE TITLE
What is the scope of data generated by HALO?

### ISSUE THREAD

**Issue by huangtao36** [btheodorou99/HALO_Inpatient#1]
According to the content of the article, I believe that the HALO model generates not only disease diagnosis codes but also complete Electronic Health Records (EHR). However, why does this code only import diagnosis files and admission records?

**Comment by btheodorou99** [comment]
Hello. Yes, the architecture can support any type of medical codes, and we have since experimented with other types of codes to similar effect. However, the experiments in the paper used only diagnosis codes (for simplicity, because our downstream experiments were diagnosis-based, and to match what was present in our other outpatient dataset) and so that is what is included here. We are happy to provide a dataset building script that includes medications and procedures as well if you would like.

**Comment by huangtao36** [comment]
Thank you for your response, and I appreciate your willingness to provide the script. If it's convenient for you, could you please send it to my email ([htao36@163.com](mailto:htao36@163.com)) or upload it to your repository?

Additionally, based on your response, it seems you have attempted generating various types of content independently, such as diagnoses, medications, programs, and more. Have you ever tried combining them all together for generation (diagnosis + medication + program + other)? I'm curious about the results of such an approach.

**Comment by mirzafarhan7** [comment]
Also, the paper mentioned about time-series data generation. Is there any seperate script on that?

**Comment by mirzafarhan7** [comment]
@huangtao36 Hi. Did the authors send you the script? I would be glad if you can share it.

**Comment by WoodPecker1111** [comment]
> Hello. Yes, the architecture can support any type of medical codes, and we have since experimented with other types of codes to similar effect. However, the experiments in the paper used only diagnosis codes (for simplicity, because our downstream experiments were diagnosis-based, and to match what was present in our other outpatient dataset) and so that is what is included here. We are happy to provide a dataset building script that includes medications and procedures as well if you would like.


Hello, I am very interested in your work! May I ask for a processing code for medications and procedures? If you are willing to share, please send it to my email: shuijing@stu.xidian.edu.cn .
Thank you very much!
