### ISSUE TITLE
add labels before converting visit codes to index

### ISSUE THREAD

**Issue by sebbarb** [btheodorou99/HALO_Inpatient#11]
Hi, amazing work and thank you for sharing your code. Just flagging that I believe that in build_dataset.py you should create labels (lines 80-88) before converting visit codes to indices (lines 48-60) since the hcup_ccs_2015_definitions_benchmark file contains the actual codes and not the indices. At present no labels are created.

**Comment by btheodorou** [comment]
Thank you very much for catching that. I've made that switch now
