### ISSUE TITLE
all labels are 0 after build_dataset

### ISSUE THREAD

**Issue by BreezeHavana** [btheodorou99/HALO_Inpatient#13]
Hi, I ran build_dataset.py and got trainDataset.pkl but found that all labels are 0. Is that correct?

**Comment by btheodorou** [comment]
There was an issue a little while back where we were adding the labels after converting the codes to indices which could've caused that. Check if the updated code fixes the issue. If not, we can explore additional issues such as the types not matching.

**Comment by BreezeHavana** [comment]
auto reply

**Comment by BreezeHavana** [comment]
auto reply
