### ISSUE TITLE
there not exists 'idToLabel.pkl'

### ISSUE THREAD

**Issue by xansar** [btheodorou99/HALO_Inpatient#14]
When I wanted to run the script 'test_model.py,' I found no 'idToLabel.pkl'. 
Then I checked the 'build_dataset.py' and could not find the 'idToLabel.pkl' codes. 
Could you upload the codes for generating 'idToLabel.pkl'?

**Comment by btheodorou** [comment]
My apologies, the dictionary was hardcoded in previously and I added the file in the test_model but not build_dataset script. I have added saving the model to the build_dataset script
