### ISSUE TITLE
The build_dataset.py does not work. Missing 'DIAGNOSIS ICD9_CODE', 'PROCEDURE ICD9_CODE', 'NDC' code

### ISSUE THREAD

**Issue by mirzafarhan7** [btheodorou99/HALO_Inpatient#2]
Hi,
Thank you for your wonderful paper. When trying to run the build_dataset.py file, it faces the error: KeyError: ('DIAGNOSIS ICD9_CODE', '2'). During the creation of the code_to_index dictionary, there was no mention of 'DIAGNOSIS ICD9_CODE', 'PROCEDURE ICD9_CODE', 'NDC' code. Where can I find them as the original admissions.csv and diagnosis_icd.csv does not have them rather they are seperated csv files in the mimic-iii

**Comment by btheodorou99** [comment]
My apologies, the script had some remnants of other explorations/experimental setups using those other files. I have removed those lines you referenced and made some other minor adjustments, so the script should work now.

**Comment by mirzafarhan7** [comment]
Thank you for your quick response!
