### ISSUE TITLE
Discretize.py throws keyerror while reading lab visits

### ISSUE THREAD

**Issue by mirzafarhan7** [btheodorou99/HALO_Inpatient#4]
```
# Convert to New Data Format
for p in (trainData + valData):
    new_visits = []
    firstVisit = True
    for v in p['visits']:
        if v[1] == []:
            new_cont = get_index(discretization, 'Age' if firstVisit else 'Days', v[3][-1])
            firstVisit = False
            new_visits.append((v[0], [], [], [new_cont]))
        else:
            new_labs = []
            new_values = []
            for l, val in zip(v[1], v[2]):
                if isCategorical[l]: # <----- THIS LINE THROWS KEY ERROR
                    if val == 1:
                        new_labs.append(labToNumber[l])
                        new_values.append(possibleValues[l].index(val))
                else:
                    if val < variableRanges[l][0] or val >= variableRanges[l][1]:
                        continue
                    
                    new_labs.append(labToNumber[l])
                    new_values.append(get_index(discretization, l, val))

            if not new_labs:
                continue
            new_cont = get_index(discretization, 'Hours', v[3][-1])
            new_visits.append((v[0], new_labs, new_values, [new_cont]))
    
    p['visits'] = new_visits

pickle.dump(trainData, open('discretized_data/trainDataset.pkl', 'wb'))
pickle.dump(valData, open('discretized_data/valDataset.pkl', 'wb')) 
```

Here the isCategorical[l] shows error as the l is a number for example 49. So here, `for l, val in zip(v[1], v[2]):` if I change it to v[0] and v[1], then the code runs otherwise not (not sure if it is doing what it i was supposed to do). What could be the issue here?

**Comment by mirzafarhan7** [comment]
Also, channel_to_id.pkl was missing from the data. Is this supposed to be a dictionary like the following?

```
{'Capillary refill rate': 0,
 'Glascow coma scale eye opening': 1,
 'Glascow coma scale motor response': 2,
 'Glascow coma scale total': 3,
 'Glascow coma scale verbal response': 4,
 'Diastolic blood pressure': 5,
 'Fraction inspired oxygen': 6,
 'Glucose': 7,
 'Heart Rate': 8,
 'Height': 9,
 'Mean blood pressure': 10,
 'Oxygen saturation': 11,
 'Respiratory rate': 12,
 'Systolic blood pressure': 13,
 'Temperature': 14,
 'Weight': 15,
 'pH': 16}
```

**Comment by btheodorou99** [comment]
Hopefully these commits fixed it. The dataset generation script basically does some extra processing (to make it applicable for multiple different data representations and use cases) that we are reversing in the discretization script. Among those is converting lab names to lab numbers, and isCategorical expects the lab names so we just need to convert them back using the idToLab mapping. I've also added the channel_to_id file (your mapping is correct). Let me know if there are any further errors, and I will try to fix them.

**Comment by mirzafarhan7** [comment]
Hi Thank you for your response. After running the committed file, the next error comes up in the else part. It works if I replace l with idToLab[l].

```
if val < variableRanges[l][0] or val >= variableRanges[l][1]:
                        continue
                    
                    new_labs.append(labToNumber[l])
                    new_values.append(get_index(discretization, l, val))
```

**Comment by mirzafarhan7** [comment]
Also, after running for a few times, a valueError comes up here:
![image](https://github.com/btheodorou99/HALO_Inpatient/assets/114263262/27cf0b24-f3ce-4465-9214-bf94271d3f2b)

**Comment by btheodorou99** [comment]
I'm not sure of the value error, but I did see some more upstream errors where I missed some labToNumber calls. Hopefully those fix everything, but we made need to do some further gatekeeping of labs. If there are further issues, you can also feel free to email me the input trainData/valData/testData files and I can debug the file end to end.

**Comment by mirzafarhan7** [comment]
Great! I will keep in touch with you. Thank you for your help!

**Comment by BreezeHavana** [comment]
> Also, after running for a few times, a valueError comes up here: ![image](https://user-images.githubusercontent.com/114263262/276695937-27cf0b24-f3ce-4465-9214-bf94271d3f2b.png)

The same. I debugged it and found "possibleValues[idToLab[l]]" is like ['To Pain', '3 To speech', '1 No Response', '4 Spontaneously', 'None', 'To Speech', 'Spontaneously', '2 To pain'], and val is an Integer 1. And there is no element 1 in that list above. The variable "possibleValues" is loaded directly from the pkl file in this repository, and I guess there might be something wrong with the file. I would be appreciated if the author check this out. Thanks! @btheodorou99

**Comment by btheodorou99** [comment]
Thanks for finding this. I have just pushed a fix. The .pkl files are correct, the issue was that we are just trying to recover the number in the possible values that the current lab value is, but we have discarded the string value. To recover it, we use the beginning position of the current lab as well as the full lab idx number stored in the variable l
