### ISSUE TITLE
Issue in the Discretized_convert.py

### ISSUE THREAD

**Issue by mirzafarhan7** [btheodorou99/HALO_Inpatient#9]
Hi. 
When running this file I faced some errors. When I printed the dataset[3]["visits"] I got output like `[([], [], [], [18.35])]`. Each patient visit has 4 elements and the last one is always float. Am I making some mistake in somewhere with data generation? For this reason, I am getting the following error:

1.  I get an IndexError for v[4]. 
```
 ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [58], in <cell line: 1>()
     22     if contType == "Age":
     23         firstVisit = False
     24     new_cont = formatCont(
     25         random.uniform(
---> 26             discretization[contType][v[4][-1]], #changing 4 to 3 removes error
     27             discretization[contType][v[4][-1] + 1], #changing 4 to 3 removes error
     28         ),
     29         contType,
     30     )
     31     new_visits.append((v[1], new_labs, new_values, [new_cont]))
     32 p["visits"] = new_visits

IndexError: tuple index out of range
```

2. I get a _TypeError if I change v[4] to v[3]
```
new_cont = formatCont(
     25         random.uniform(
---> 26             discretization[contType][v[3][-1]],
     27             discretization[contType][v[3][-1] + 1],
     28         ),
     29         contType,
     30     )
```

I would be very grateful if you could point me in the right direction like where to look for solving the issue.

**Comment by btheodorou99** [comment]
Hello, yes the indices in discretized_convert.py were one too high throughout the file. We have fixed that error and pushed an update. However, the data you discuss at the top of the comments looks like it has already been discretized. The output of generate.py has integers as the v[3] element and that is a float (which we are trying to achieve as an output). Can you check what the output of the generate.py step is?

**Comment by mirzafarhan7** [comment]
Here is the first element of the generate.py output.
[{'visits': [([27,
     44,
     124,
     172,
     314,
     324,
     355,
     496,
     517,
     552,
     770,
     808,
     1025,
     1149,
     1450,
     1580,
     1601,
     1638,
     1655,
     1813,
     1820,
     2022,
     2080,
     2103,
     2446,
     2458,
     2465,
     2469,
     2572,
     2634,
     2922,
     2931,
     3077,
     3219,
     3306,
     3341,
     3382,
     3453,
     3523,
     3603,
     3787],
    [],
    [],
    [9])],
  'labels': array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)},

**Comment by btheodorou** [comment]
That looks different than the data in your first message (specifically, the final element in the visit tuple is [9] rather than [18.35]. This one should be ready to discretize with the updated code.

**Comment by mirzafarhan7** [comment]
I was able to do the discretization. Thanks!
